import type { Meta, StoryObj } from '@storybook/preact';
import { Button } from '../components/Button.tsx';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Outline: Story;
export declare const Ghost: Story;
export declare const Small: Story;
export declare const Medium: Story;
export declare const Large: Story;
export declare const Disabled: Story;
export declare const Loading: Story;
export declare const FullWidth: Story;
export declare const AllVariants: Story;
export declare const AllSizes: Story;
export declare const AllStates: Story;
